server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.101.76.249:3306/weather?characterEncoding=utf-8
    username: root
    password: root